// GET All games
GET http://localhost:5190/games

###
//GET ID
GET http://localhost:5190/games/2

###

POST http://localhost:5190/games
Content-Type: application/json

{
    "name": "Test Gameover",
    "genreId": 3,
    "price": 9.99,
    "releaseDate": "2026-08-26"
}

###

PUT http://localhost:5190/games/2
Content-Type: application/json

{
    "name": "Hollow Knight",
    "genreId": 2,
    "price": 20.00,
    "releaseDate": "2017-02-24"
}
###
DELETE http://localhost:5190/games/4